#!/usr/bin/env bash
# Displays the PID and process name of processes whose name contain the word 'bash'

for pid in /proc/[0-9]*; do
  if [ -r "$pid/comm" ]; then
    comm=$(cat "$pid/comm")
    if [[ "$comm" == *bash* ]]; then
      echo "$(basename "$pid") $comm"
    fi
  fi
done

